# Generated by Django 5.2 on 2026-09-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
