# Generated by Django 5.2 on 2026-09-15 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_comment_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="status",
        ),
    ]
