# Generated by Django 5.2 on 2026-09-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_remove_comment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
