# Generated by Django 5.2 on 2026-10-03 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_comment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="name",
        ),
    ]
